[package]
name = "build-shaders"
version = "0.0.0"
publish = false
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]


[build-dependencies]
spirv-builder = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "76b96c0e05"}
