name: 'Setup Rust Environment'
description: 'Installs Rust toolchain and sets up dependency caching'

inputs:
  components:
    description: 'Additional Rust components to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      shell: bash
      run: |
        rustup toolchain install stable --profile minimal
        rustup default stable
        
        # Install additional components if specified
        if [ -n "${{ inputs.components }}" ]; then
          rustup component add ${{ inputs.components }}
        fi
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
