[package]
name = "rust-lut"
version = "0.1.0"
edition = "2021"

[dependencies]
# Image processing
image = "0.25.5"
glam = "0.30.0"
rayon = { version = "1.10", optional = true }

[features]
default = ["rayon"]
rayon = ["dep:rayon"]
