[package]
name = "compute-shader"
version = "0.0.0"
publish = false
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "76b96c0e05"}

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
rayon = "1.5"
