name: Benchmark

on:
  push:
    branches: [ main ]
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual triggering

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for comparing benchmarks
      
      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust
      
      - name: Install OpenCL Runtime
        uses: ./.github/actions/install-opencl
          
      - name: Install LLVM SPIRV 15 and Clang 15
        uses: ./.github/actions/install-llvm-spirv

      - name: Run benchmarks
        run: cargo bench --no-default-features --features rayon -- --output-format bencher | tee benchmark_results.txt
      
      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: benchmark_results.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          # Mention users when the performance regression is detected
          alert-comment-cc-users: '@SoapSeller'
