name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    name: Build Release
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rust-lut
            asset_name: rust-lut-linux-amd64
          - os: macos-latest
            artifact_name: rust-lut
            asset_name: rust-lut-macos-amd64
          - os: windows-latest
            artifact_name: rust-lut.exe
            asset_name: rust-lut-windows-amd64.exe

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
      
      - name: Install OpenCL CPU Runtime (POCL) on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pocl-opencl-icd ocl-icd-opencl-dev

          # Install clinfo to verify the installation
          sudo apt-get install -y clinfo

          # Verify that OpenCL devices are detected
          clinfo

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream
